# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L9rkb4kgQevpR2nW70RMBJbbJXYAZM9l
"""

import pandas as pd
import numpy as np

print("1. Generating State-Specific Historical Weather...")
# Load the calendar to get exact dates
df_calendar = pd.read_csv('calendar.csv')

# Create an array representing the days for our mathematical wave
days = np.arange(len(df_calendar))

# Define our State Climate Profiles
climate_profiles = {
    'CA': {'base_temp': 65, 'amplitude': 15, 'cold_thresh': 40, 'hot_thresh': 95},  # Mild & Stable
    'TX': {'base_temp': 75, 'amplitude': 25, 'cold_thresh': 32, 'hot_thresh': 100}, # Hot Summers
    'WI': {'base_temp': 45, 'amplitude': 40, 'cold_thresh': 15, 'hot_thresh': 90}   # Cold Winters
}

weather_dataframes = []

# Generate a unique weather timeline for each state
for state, profile in climate_profiles.items():
    # Mathematical Sine wave to simulate Summer/Winter cycles
    temp = profile['base_temp'] + profile['amplitude'] * np.sin(2 * np.pi * (days - 100) / 365)

    # Add random daily noise so it looks like real, unpredictable weather
    temp += np.random.normal(0, 5, len(df_calendar))

    # Flag extreme weather based on that specific state's tolerance
    extreme_flag = ((temp < profile['cold_thresh']) | (temp > profile['hot_thresh'])).astype(int)

    # Build a temporary dataframe for this state
    df_state = df_calendar[['wm_yr_wk']].copy()
    df_state['state_id'] = state
    df_state['avg_temp_F'] = np.round(temp, 1)
    df_state['extreme_weather'] = extreme_flag

    weather_dataframes.append(df_state)

# Combine all 3 states together
df_weather_daily = pd.concat(weather_dataframes)

# Roll up daily weather to weekly averages and max extreme flags
df_weather_weekly = df_weather_daily.groupby(['wm_yr_wk', 'state_id']).agg({
    'avg_temp_F': 'mean',
    'extreme_weather': 'max'
}).reset_index()

# Save the realistic weather file
df_weather_weekly.to_csv('historical_weather_state_specific.csv', index=False)
print("✅ State-Specific Weather Simulated and Saved!")

import pandas as pd
import numpy as np

print("1. Generating State-Specific Historical Weather...")
# Load the calendar to get exact dates
df_calendar = pd.read_csv('calendar.csv')

# Create an array representing the days for our mathematical wave
days = np.arange(len(df_calendar))

# Define our State Climate Profiles
climate_profiles = {
    'CA': {'base_temp': 65, 'amplitude': 15, 'cold_thresh': 40, 'hot_thresh': 95},  # Mild & Stable
    'TX': {'base_temp': 75, 'amplitude': 25, 'cold_thresh': 32, 'hot_thresh': 100}, # Hot Summers
    'WI': {'base_temp': 45, 'amplitude': 40, 'cold_thresh': 15, 'hot_thresh': 90}   # Cold Winters
}

weather_dataframes = []

# Generate a unique weather timeline for each state
for state, profile in climate_profiles.items():
    # Mathematical Sine wave to simulate Summer/Winter cycles
    temp = profile['base_temp'] + profile['amplitude'] * np.sin(2 * np.pi * (days - 100) / 365)

    # Add random daily noise so it looks like real, unpredictable weather
    temp += np.random.normal(0, 5, len(df_calendar))

    # Flag extreme weather based on that specific state's tolerance
    extreme_flag = ((temp < profile['cold_thresh']) | (temp > profile['hot_thresh'])).astype(int)

    # Build a temporary dataframe for this state
    df_state = df_calendar[['wm_yr_wk']].copy()
    df_state['state_id'] = state
    df_state['avg_temp_F'] = np.round(temp, 1)
    df_state['extreme_weather'] = extreme_flag

    weather_dataframes.append(df_state)

# Combine all 3 states together
df_weather_daily = pd.concat(weather_dataframes)

# Roll up daily weather to weekly averages and max extreme flags
df_weather_weekly = df_weather_daily.groupby(['wm_yr_wk', 'state_id']).agg({
    'avg_temp_F': 'mean',
    'extreme_weather': 'max'
}).reset_index()

# Save the realistic weather file
df_weather_weekly.to_csv('historical_weather_state_specific.csv', index=False)
print("✅ State-Specific Weather Simulated and Saved!")

import pandas as pd

print("Merging location-specific weather into Master Dataset...")

# Load your master dataset and the new weather dataset
df_master = pd.read_csv('master_dataset.csv')
df_weather = pd.read_csv('historical_weather_state_specific.csv')

# The Magic Merge: Matches the week AND the state!
df_master = pd.merge(df_master, df_weather, on=['wm_yr_wk', 'state_id'], how='left')

df_master.to_csv('master_dataset_final.csv', index=False)
print("✅ SUCCESS! Your AI now knows the difference between a Texas Heatwave and a Wisconsin Winter.")

import pandas as pd
import lightgbm as lgb
from prophet import Prophet
from sklearn.metrics import mean_absolute_error
import joblib
import warnings
warnings.filterwarnings('ignore')

print("1. Loading Head SKU Data & Calendar...")
df = pd.read_csv('data_head_skus.csv')
df_calendar = pd.read_csv('calendar.csv')

# --- MERGE WEATHER DATA ---
# Load the generated historical weather data
df_weather = pd.read_csv('historical_weather_state_specific.csv')
# Merge weather into the main dataframe
df = pd.merge(df, df_weather, on=['wm_yr_wk', 'state_id'], how='left')


# --- FIXING DATES FOR PROPHET ---
# Prophet needs a column named 'ds' (dates) and 'y' (target).
# We map the week ID (wm_yr_wk) to the actual starting date of that week.
week_to_date = df_calendar.groupby('wm_yr_wk')['date'].min().reset_index()
df = pd.merge(df, week_to_date, on='wm_yr_wk', how='left')
df.rename(columns={'date': 'ds', 'sales_quantity': 'y'}, inplace=True)
df['ds'] = pd.to_datetime(df['ds'])

# We will train the models for ONE specific top-selling item to prove the concept.
# Let's pick the absolute best-selling item in CA_1.
top_item = df['item_id'].value_counts().index[0]
df_item = df[(df['item_id'] == top_item) & (df['store_id'] == 'CA_1')].copy()

# Sort chronologically!
df_item = df_item.sort_values('ds').reset_index(drop=True)

# --- CHRONOLOGICAL SPLIT (80% Train, 20% Test) ---
print(f"2. Splitting data for Item: {top_item}...")
split_idx = int(len(df_item) * 0.8)
train = df_item.iloc[:split_idx]
test = df_item.iloc[split_idx:]

print(f"Training on {len(train)} weeks, Testing on {len(test)} weeks.")


# =========================================================
# MODEL 1: FACEBOOK PROPHET (The Trend Master)
# =========================================================
print("\n3. Training Facebook Prophet...")

# Initialize Prophet
m_prophet = Prophet(yearly_seasonality=True, weekly_seasonality=False, daily_seasonality=False)

# Add our custom Multi-Signal features as "regressors"
m_prophet.add_regressor('sell_price')
m_prophet.add_regressor('has_event')
m_prophet.add_regressor('extreme_weather') # Using the weather we built!

# Train
m_prophet.fit(train[['ds', 'y', 'sell_price', 'has_event', 'extreme_weather']])

# Predict
future = test[['ds', 'sell_price', 'has_event', 'extreme_weather']].copy()
forecast_prophet = m_prophet.predict(future)

# Evaluate
mae_prophet = mean_absolute_error(test['y'], forecast_prophet['yhat'])
print(f"✅ Prophet MAE: {mae_prophet:.2f} units")


# =========================================================
# MODEL 2: LIGHTGBM (The Shock Absorber)
# =========================================================
print("\n4. Training LightGBM...")

# Define what the AI learns from (X)
features = ['sell_price', 'has_event', 'extreme_weather', 'avg_temp_F', 'dept_total_sales']
X_train, y_train = train[features], train['y']
X_test, y_test = test[features], test['y']

# Initialize & Train
m_lgbm = lgb.LGBMRegressor(n_estimators=150, learning_rate=0.05, max_depth=6, random_state=42)
m_lgbm.fit(X_train, y_train)

# Predict & Evaluate
forecast_lgbm = m_lgbm.predict(X_test)
mae_lgbm = mean_absolute_error(y_test, forecast_lgbm)
print(f"✅ LightGBM MAE: {mae_lgbm:.2f} units")

# =========================================================
# THE HYBRID ENSEMBLE (Hackathon Gold)
# =========================================================
# Average the two models together to get the best of both worlds
hybrid_forecast = (forecast_prophet['yhat'].values + forecast_lgbm) / 2
mae_hybrid = mean_absolute_error(y_test, hybrid_forecast)

print(f"\n🏆 HYBRID ENSEMBLE MAE: {mae_hybrid:.2f} units")
if mae_hybrid < mae_lgbm and mae_hybrid < mae_prophet:
    print("-> The Ensemble beat both individual models! This proves our architecture works.")

# Save the LightGBM model for the Streamlit UI
joblib.dump(m_lgbm, 'lgbm_head_model.pkl')
print("\nModel saved as 'lgbm_head_model.pkl'. Ready for the Dashboard!")

import numpy as np

def calculate_wmape(actual, forecast):
    """Calculates the Weighted Mean Absolute Percentage Error."""
    return (np.sum(np.abs(actual - forecast)) / np.sum(actual)) * 100

# --- FIX: Move these out of the function (no indentation) ---
actual_values = np.array([100, 150, 200])
forecast_values = np.array([110, 140, 210])

# This line must NOT be indented
wmape_score = calculate_wmape(actual_values, forecast_values)

# 3. View the result
print(f"The WMAPE is: {wmape_score:.2f}%")

