# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ARWp31UbrRRQfcSb4oeWvxa-tSLGi-yd
"""

!pip install pandas numpy matplotlib seaborn scikit-learn statsmodels plotly -q

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import warnings
warnings.filterwarnings('ignore')

from sklearn.metrics import mean_absolute_error, mean_squared_error
from google.colab import files

plt.style.use('seaborn-v0_8-whitegrid')
pd.set_option('display.float_format', '{:.2f}'.format)
print('✅ All libraries loaded successfully!')

# ---- OPTION A: Upload from your computer ----
uploaded = files.upload()  # Select master_dataset_final.csv

import io
filename = list(uploaded.keys())[0]
df_raw = pd.read_csv(io.BytesIO(uploaded[filename]))

print(f'✅ Loaded: {df_raw.shape[0]:,} rows × {df_raw.shape[1]} columns')
df_raw.head()

print('=== DATASET OVERVIEW ===')
print(f'Shape          : {df_raw.shape}')
print(f'Unique items   : {df_raw["item_id"].nunique()}')
print(f'Unique stores  : {df_raw["store_id"].nunique()}')
print(f'Week range     : {df_raw["wm_yr_wk"].min()} → {df_raw["wm_yr_wk"].max()}')
print(f'Total weeks    : {df_raw["wm_yr_wk"].nunique()}')
print()
print('=== MISSING VALUES ===')
print(df_raw.isnull().sum())
print()
print('=== SALES QUANTITY STATS ===')
print(df_raw['sales_quantity'].describe())

# ── Sales distribution per item (to identify long tail) ──────────────────
item_sales = df_raw.groupby('item_id')['sales_quantity'].sum().sort_values(ascending=False).reset_index()
item_sales['cum_pct'] = item_sales['sales_quantity'].cumsum() / item_sales['sales_quantity'].sum() * 100
item_sales['rank'] = range(1, len(item_sales)+1)

fig, axes = plt.subplots(1, 2, figsize=(16, 5))

# Bar chart of total sales per item
axes[0].bar(range(len(item_sales)), item_sales['sales_quantity'], color=['#e74c3c' if x <= 20 else '#3498db' for x in range(len(item_sales))])
axes[0].set_title('Total Sales Per Item (Red = Top 20 / Blue = Long Tail)', fontsize=13)
axes[0].set_xlabel('Item Rank')
axes[0].set_ylabel('Total Sales Quantity')

# Pareto curve
axes[1].plot(item_sales['rank'], item_sales['cum_pct'], color='#2c3e50', linewidth=2)
axes[1].axhline(y=80, color='red', linestyle='--', label='80% threshold')
axes[1].fill_between(item_sales['rank'], item_sales['cum_pct'], alpha=0.1)
axes[1].set_title('Pareto Curve — Cumulative Sales %', fontsize=13)
axes[1].set_xlabel('Number of Items (ranked by sales)')
axes[1].set_ylabel('Cumulative % of Total Sales')
axes[1].legend()

plt.tight_layout()
plt.savefig('pareto_analysis.png', dpi=150, bbox_inches='tight')
plt.show()
# Find the 80/20 cut
top_items_80 = item_sales[item_sales['cum_pct'] <= 80]
print(f'\n📊 {len(top_items_80)} items ({len(top_items_80)/len(item_sales)*100:.1f}%) drive 80% of sales → "Head" SKUs')
print(f'📊 {len(item_sales)-len(top_items_80)} items ({(len(item_sales)-len(top_items_80))/len(item_sales)*100:.1f}%) make remaining 20% → "Long Tail" SKUs')

# ── Intermittency Analysis ────────────────────────────────────────────────
# ADI = Average Demand Interval | CV2 = Coefficient of Variation squared
# Croston classification matrix (Syntetos et al. 2005)

def classify_sku(series):
    """Classify SKU demand pattern: Smooth / Erratic / Intermittent / Lumpy"""
    non_zero = series[series > 0]
    if len(non_zero) == 0:
        return 'Dead', np.nan, np.nan

    # ADI: average interval between non-zero demands
    periods_with_demand = (series > 0).sum()
    total_periods = len(series)
    adi = total_periods / periods_with_demand if periods_with_demand > 0 else np.inf

    # CV2: squared coefficient of variation of demand sizes
    cv2 = (non_zero.std() / non_zero.mean()) ** 2 if non_zero.mean() > 0 else 0

    if adi < 1.32 and cv2 < 0.49:   return 'Smooth', adi, cv2
    elif adi < 1.32 and cv2 >= 0.49: return 'Erratic', adi, cv2
    elif adi >= 1.32 and cv2 < 0.49: return 'Intermittent', adi, cv2
    else:                             return 'Lumpy', adi, cv2

# Aggregate to item level (sum across stores/states per week)
weekly_item = df_raw.groupby(['item_id', 'wm_yr_wk'])['sales_quantity'].sum().reset_index()

sku_profiles = []
for item, grp in weekly_item.groupby('item_id'):
    cat, adi, cv2 = classify_sku(grp['sales_quantity'])
    total_sales = grp['sales_quantity'].sum()
    zero_pct = (grp['sales_quantity'] == 0).mean() * 100
    sku_profiles.append({'item_id': item, 'category': cat, 'ADI': adi, 'CV2': cv2,
                         'total_sales': total_sales, 'zero_weeks_pct': zero_pct})

sku_df = pd.DataFrame(sku_profiles)
print('=== SKU DEMAND CLASSIFICATION ===')
print(sku_df['category'].value_counts())
print()
sku_df.head(10)

# ── Demand Classification Plot (ADI vs CV2 matrix) ────────────────────────
fig, ax = plt.subplots(figsize=(10, 7))

colors = {'Smooth': '#27ae60', 'Erratic': '#f39c12', 'Intermittent': '#3498db', 'Lumpy': '#e74c3c', 'Dead': '#95a5a6'}
for cat, grp in sku_df[sku_df['category'] != 'Dead'].groupby('category'):
    ax.scatter(grp['ADI'], grp['CV2'], label=cat, color=colors[cat], s=grp['total_sales']/500 + 30, alpha=0.7, edgecolors='white')

ax.axvline(x=1.32, color='black', linestyle='--', linewidth=1.5, label='ADI = 1.32')
ax.axhline(y=0.49, color='black', linestyle=':', linewidth=1.5, label='CV² = 0.49')

# Quadrant labels
ax.text(1.05, 0.1, 'SMOOTH', fontsize=11, color='#27ae60', fontweight='bold')
ax.text(1.05, 1.2, 'ERRATIC', fontsize=11, color='#f39c12', fontweight='bold')
ax.text(1.7, 0.1, 'INTERMITTENT', fontsize=11, color='#3498db', fontweight='bold')
ax.text(1.7, 1.2, 'LUMPY', fontsize=11, color='#e74c3c', fontweight='bold')

ax.set_xlabel('ADI (Average Demand Interval) — Higher = More Intermittent', fontsize=12)
ax.set_ylabel('CV² (Demand Variability) — Higher = More Variable', fontsize=12)
ax.set_title('SKU Demand Classification Matrix\n(Syntetos-Boylan 2005)', fontsize=14)
ax.legend(loc='upper right')
plt.tight_layout()
plt.savefig('sku_classification_matrix.png', dpi=150, bbox_inches='tight')
plt.show()

#── Strategy: Define Long Tail by combining sales rank + demand pattern ───
# You can adjust these thresholds based on your business definition

# Rank items by total sales
item_rank = weekly_item.groupby('item_id')['sales_quantity'].sum().rank(ascending=False).astype(int)
sku_df['sales_rank'] = sku_df['item_id'].map(item_rank)
sku_df['is_long_tail'] = (
    (sku_df['sales_rank'] > len(sku_df) * 0.4) |  # Bottom 60% by sales volume
    (sku_df['category'].isin(['Intermittent', 'Lumpy']))  # OR intermittent/lumpy pattern
)

long_tail_items = sku_df[sku_df['is_long_tail']]['item_id'].tolist()
head_items = sku_df[~sku_df['is_long_tail']]['item_id'].tolist()

print(f'📦 Long-Tail SKUs : {len(long_tail_items)} items → Will use Croston SBA')
print(f'📈 Head SKUs      : {len(head_items)} items → Can use ETS/ARIMA')
print()
print('Long-Tail SKU demand patterns:')
print(sku_df[sku_df['is_long_tail']]['category'].value_counts())

def croston_sba(demand: np.ndarray, alpha: float = 0.1, n_periods: int = 8):
    """
    Syntetos-Boylan Approximation (SBA) — bias-corrected Croston method.

    Parameters
    ----------
    demand    : array-like, historical demand series
    alpha     : smoothing parameter (0 < alpha < 1). Lower = more stable.
    n_periods : number of future periods to forecast

    Returns
    -------
    dict with forecast values, fitted values, and components
    """
    demand = np.asarray(demand, dtype=float)
    n = len(demand)

    # Handle edge case: all zeros
    if demand.sum() == 0:
        return {
            'forecast': np.zeros(n_periods),
            'fitted': np.zeros(n),
            'z_smooth': np.zeros(n),
            'p_smooth': np.zeros(n),
            'alpha': alpha
        }

    # Initialization (use first non-zero demand)
    first_nz = demand[demand > 0]
    z = first_nz[0]        # initial smoothed demand size
    p = 1.0                # initial smoothed interval

    z_history = np.zeros(n)
    p_history = np.zeros(n)
    fitted = np.zeros(n)

    q = 1  # periods since last non-zero demand

    for t in range(n):
        if demand[t] > 0:
            # Update smoothed demand size
            z = alpha * demand[t] + (1 - alpha) * z
            # Update smoothed interval
            p = alpha * q + (1 - alpha) * p
            q = 1  # reset interval counter
        else:
            q += 1  # increment interval, no update to z or p

        z_history[t] = z
        p_history[t] = p

        # SBA forecast = bias-corrected Croston
        fitted[t] = (1 - alpha / 2) * (z / p)

    # Future forecast (constant, last fitted value)
    last_forecast = (1 - alpha / 2) * (z / p)
    forecast = np.full(n_periods, last_forecast)

    return {
        'forecast': forecast,
        'fitted': fitted,
        'z_smooth': z_history,
        'p_smooth': p_history,
        'alpha': alpha,
        'last_z': z,
        'last_p': p
    }


print('✅ Croston SBA function defined!')

def optimize_alpha(demand: np.ndarray, alpha_range: np.ndarray = None, metric: str = 'MAE'):
    """
    Find the best alpha via walk-forward validation.
    Uses last 20% of data as validation window.
    """
    if alpha_range is None:
        alpha_range = np.arange(0.05, 0.55, 0.05)

    n = len(demand)
    val_start = int(n * 0.8)
    train = demand[:val_start]
    val = demand[val_start:]

    best_alpha = 0.1
    best_score = np.inf

    for a in alpha_range:
        result = croston_sba(train, alpha=a, n_periods=len(val))
        preds = result['forecast']

        if metric == 'MAE':
            score = mean_absolute_error(val, preds)
        elif metric == 'RMSE':
            score = np.sqrt(mean_squared_error(val, preds))

        if score < best_score:
            best_score = score
            best_alpha = a

    return best_alpha, best_score


print('✅ Alpha optimizer defined!')

# ── Prepare weekly series for each item (aggregated across all stores) ────
# You can also run at store×item level — just change groupby keys

# Create complete weekly grid (fill missing weeks with 0)
all_weeks = sorted(df_raw['wm_yr_wk'].unique())
all_items = df_raw['item_id'].unique()

# Full grid
grid = pd.MultiIndex.from_product([all_items, all_weeks], names=['item_id', 'wm_yr_wk'])
weekly_agg = (df_raw.groupby(['item_id', 'wm_yr_wk'])['sales_quantity']
              .sum()
              .reindex(grid, fill_value=0)
              .reset_index())

print(f'✅ Weekly grid created: {weekly_agg.shape}')
print(f'   Items: {weekly_agg["item_id"].nunique()} | Weeks: {weekly_agg["wm_yr_wk"].nunique()}')
weekly_agg.head()

FORECAST_WEEKS = 8   # How many weeks ahead to forecast
OPTIMIZE_ALPHA = True  # Set False to use fixed alpha=0.1 (faster)

results = []
fitted_store = {}

items_to_model = long_tail_items  # Change to all_items to run on all

print(f'🔄 Training Croston SBA on {len(items_to_model)} long-tail SKUs...')

for i, item in enumerate(items_to_model):
    series = weekly_agg[weekly_agg['item_id'] == item]['sales_quantity'].values

    if OPTIMIZE_ALPHA:
        best_alpha, val_score = optimize_alpha(series)
    else:
        best_alpha = 0.1
        val_score = np.nan

    # Fit on full series
    res = croston_sba(series, alpha=best_alpha, n_periods=FORECAST_WEEKS)

    # Compute in-sample metrics
    actual = series
    fitted = res['fitted']
    mae = mean_absolute_error(actual, fitted)
    rmse = np.sqrt(mean_squared_error(actual, fitted))

    # Store fitted values for plotting
    fitted_store[item] = {
        'actual': actual,
        'fitted': fitted,
        'forecast': res['forecast'],
        'alpha': best_alpha
    }

    # Append forecast rows
    for h, fcast_val in enumerate(res['forecast'], 1):
        results.append({
            'item_id': item,
            'horizon': h,
            'forecast': round(fcast_val, 2),
            'alpha': best_alpha,
            'in_sample_MAE': round(mae, 3),
            'in_sample_RMSE': round(rmse, 3),
            'val_MAE': round(val_score, 3) if not np.isnan(val_score) else None,
            'demand_category': sku_df[sku_df['item_id']==item]['category'].values[0] if len(sku_df[sku_df['item_id']==item]) > 0 else 'Unknown'
        })

    if (i + 1) % 10 == 0:
        print(f'   {i+1}/{len(items_to_model)} done...')

forecast_df = pd.DataFrame(results)
print(f'\n✅ Forecasting complete! Shape: {forecast_df.shape}')
forecast_df.head(10)

def plot_sku_forecast(item_id, weeks=all_weeks, show_last_n=52):
    """Plot actual + fitted + forecast for a single SKU."""
    data = fitted_store[item_id]
    actual = data['actual'][-show_last_n:]
    fitted = data['fitted'][-show_last_n:]
    forecast = data['forecast']
    alpha = data['alpha']

    week_labels = list(weeks[-show_last_n:]) + [f'F+{h}' for h in range(1, FORECAST_WEEKS+1)]

    fig = go.Figure()
    fig.add_trace(go.Bar(x=week_labels[:show_last_n], y=actual, name='Actual', marker_color='#3498db', opacity=0.7))
    fig.add_trace(go.Scatter(x=week_labels[:show_last_n], y=fitted, mode='lines', name='SBA Fitted',
                             line=dict(color='#e74c3c', width=2)))
    fig.add_trace(go.Scatter(x=week_labels[show_last_n:], y=forecast, mode='lines+markers',
                             name='SBA Forecast', line=dict(color='#27ae60', width=2.5, dash='dash'),
                             marker=dict(size=8)))

    # Confidence band (simple ±1 std of actuals)
    std = np.std(actual)
    fig.add_trace(go.Scatter(x=week_labels[show_last_n:], y=forecast+std, fill=None, mode='lines',
                             line=dict(color='rgba(39,174,96,0.2)'), showlegend=False))
    fig.add_trace(go.Scatter(x=week_labels[show_last_n:], y=np.maximum(forecast-std, 0), fill='tonexty',
                             mode='lines', line=dict(color='rgba(39,174,96,0.2)'),
                             fillcolor='rgba(39,174,96,0.15)', name='±1 Std Band'))

    fig.update_layout(
        title=f'Croston SBA Forecast — {item_id} (α={alpha:.2f})',
        xaxis_title='Week', yaxis_title='Sales Quantity',
        height=450, template='plotly_white',
        legend=dict(orientation='h', yanchor='bottom', y=1.02)
    )
    fig.show()

# Plot the first 3 long-tail SKUs
for item in long_tail_items[:3]:
    plot_sku_forecast(item)

def walk_forward_eval(item_id, n_test=8, step=1):
    """Walk-forward validation: train on t, predict t+1, slide window."""
    series = weekly_agg[weekly_agg['item_id'] == item_id]['sales_quantity'].values
    n = len(series)
    train_end = n - n_test

    preds, actuals = [], []
    for t in range(train_end, n):
        train = series[:t]
        res = croston_sba(train, alpha=0.1, n_periods=1)
        preds.append(res['forecast'][0])
        actuals.append(series[t])

    mae = mean_absolute_error(actuals, preds)
    rmse = np.sqrt(mean_squared_error(actuals, preds))

    # Bias
    bias = np.mean(np.array(preds) - np.array(actuals))

    # MASE (Mean Absolute Scaled Error) — naive benchmark = last week demand
    naive_mae = mean_absolute_error(actuals[1:], actuals[:-1]) if len(actuals) > 1 else 1
    mase = mae / naive_mae if naive_mae > 0 else np.nan

    return {'item_id': item_id, 'MAE': mae, 'RMSE': rmse, 'Bias': bias, 'MASE': mase,
            'actuals': actuals, 'preds': preds}


# Run walk-forward on all long-tail items
print('🔄 Running walk-forward validation...')
eval_results = []
for item in long_tail_items:
    ev = walk_forward_eval(item)
    eval_results.append({k: v for k, v in ev.items() if k not in ['actuals', 'preds']})

eval_df = pd.DataFrame(eval_results)
print('\n=== WALK-FORWARD VALIDATION RESULTS ===')
print(eval_df.describe().round(3))
print()
print('MASE < 1.0 means our model beats the naive forecast ✅')
print(f'% items with MASE < 1.0: {(eval_df["MASE"] < 1.0).mean()*100:.1f}%')

# ── Metrics distribution plot ─────────────────────────────────────────────
fig, axes = plt.subplots(1, 3, figsize=(15, 4))

eval_df['MAE'].hist(ax=axes[0], bins=20, color='#3498db', edgecolor='white')
axes[0].set_title('MAE Distribution', fontsize=12)
axes[0].set_xlabel('MAE')

eval_df['MASE'].dropna().hist(ax=axes[1], bins=20, color='#27ae60', edgecolor='white')
axes[1].axvline(x=1.0, color='red', linestyle='--', label='Naive baseline')
axes[1].set_title('MASE Distribution (< 1 = beats naive)', fontsize=12)
axes[1].set_xlabel('MASE')
axes[1].legend()

eval_df['Bias'].hist(ax=axes[2], bins=20, color='#e74c3c', edgecolor='white')
axes[2].axvline(x=0, color='black', linestyle='--', label='Zero bias')
axes[2].set_title('Forecast Bias (0 = unbiased)', fontsize=12)
axes[2].set_xlabel('Bias')
axes[2].legend()

plt.suptitle('Croston SBA — Model Evaluation Metrics', fontsize=14, y=1.02)
plt.tight_layout()
plt.savefig('evaluation_metrics.png', dpi=150, bbox_inches='tight')
plt.show()

# How does alpha choice affect forecast for a sample SKU?
sample_item = long_tail_items[0]
series = weekly_agg[weekly_agg['item_id'] == sample_item]['sales_quantity'].values
alphas = [0.05, 0.10, 0.20, 0.30, 0.50]

fig = go.Figure()
fig.add_trace(go.Bar(x=list(range(len(series[-30:]))),
                     y=series[-30:], name='Actual', marker_color='#bdc3c7', opacity=0.8))

palette = ['#e74c3c', '#e67e22', '#27ae60', '#3498db', '#9b59b6']
for a, col in zip(alphas, palette):
    res = croston_sba(series, alpha=a, n_periods=8)
    fitted_last30 = res['fitted'][-30:]
    forecast_vals = res['forecast']
    all_vals = list(fitted_last30) + list(forecast_vals)
    x_all = list(range(30)) + list(range(30, 38))
    fig.add_trace(go.Scatter(x=x_all, y=all_vals, mode='lines', name=f'α={a}',
                             line=dict(color=col, width=2)))

fig.add_vline(x=29.5, line_dash='dash', line_color='black', annotation_text='Forecast Start')
fig.update_layout(
    title=f'Alpha Sensitivity — {sample_item}',
    xaxis_title='Time Period', yaxis_title='Sales Quantity',
    height=400, template='plotly_white'
)
fig.show()
print('Low alpha (0.05) = slow, stable response | High alpha (0.50) = fast, reactive')

# ── 1. Forecast output table ──────────────────────────────────────────────
# Add readable week labels to forecast
last_week = df_raw['wm_yr_wk'].max()
forecast_df['forecast_week_offset'] = forecast_df['horizon']
forecast_df['note'] = forecast_df['horizon'].apply(lambda h: f'Week +{h} from {last_week}')

# Pivot to wide format (one row per item)
forecast_wide = forecast_df.pivot_table(
    index=['item_id', 'alpha', 'in_sample_MAE', 'demand_category'],
    columns='horizon',
    values='forecast'
).reset_index()
forecast_wide.columns = [f'wk_{c}' if isinstance(c, int) else c for c in forecast_wide.columns]

# Merge eval metrics
forecast_wide = forecast_wide.merge(eval_df[['item_id', 'MASE', 'Bias']], on='item_id', how='left')

forecast_wide.to_csv('croston_sba_forecasts.csv', index=False)
print(f'✅ Forecast saved: croston_sba_forecasts.csv ({len(forecast_wide)} rows)')
forecast_wide.head()

# ── 2. Download all outputs ───────────────────────────────────────────────
files.download('croston_sba_forecasts.csv')
# files.download('pareto_analysis.png')
# files.download('evaluation_metrics.png')
# files.download('sku_classification_matrix.png')

def moving_average_forecast(demand, window=4, n_periods=8):
    """Simple moving average baseline."""
    ma = np.convolve(demand, np.ones(window)/window, mode='valid')
    last_val = ma[-1] if len(ma) > 0 else np.mean(demand)
    return np.full(n_periods, last_val)

# Compare on a sample of long-tail items
comparison = []
for item in long_tail_items[:20]:
    series = weekly_agg[weekly_agg['item_id'] == item]['sales_quantity'].values
    n = len(series)
    test_size = 8
    train, test = series[:-test_size], series[-test_size:]

    # Croston SBA
    res_sba = croston_sba(train, alpha=0.1, n_periods=test_size)
    mae_sba = mean_absolute_error(test, res_sba['forecast'])

    # Moving Average
    fc_ma = moving_average_forecast(train, window=4, n_periods=test_size)
    mae_ma = mean_absolute_error(test, fc_ma)

    comparison.append({'item_id': item, 'MAE_SBA': mae_sba, 'MAE_MA': mae_ma,
                       'SBA_wins': mae_sba < mae_ma})

comp_df = pd.DataFrame(comparison)
print('=== CROSTON SBA vs MOVING AVERAGE ===')
print(f"SBA wins: {comp_df['SBA_wins'].sum()}/{len(comp_df)} items ({comp_df['SBA_wins'].mean()*100:.1f}%)")
print(f"Avg MAE — SBA: {comp_df['MAE_SBA'].mean():.2f} | MA: {comp_df['MAE_MA'].mean():.2f}")

# Visual comparison
fig, ax = plt.subplots(figsize=(10, 5))
x = np.arange(len(comp_df))
ax.bar(x - 0.2, comp_df['MAE_SBA'], 0.4, label='Croston SBA', color='#27ae60')
ax.bar(x + 0.2, comp_df['MAE_MA'], 0.4, label='Moving Avg (4w)', color='#e74c3c')
ax.set_xticks(x)
ax.set_xticklabels(comp_df['item_id'], rotation=45, ha='right', fontsize=8)
ax.set_ylabel('MAE (lower is better)')
ax.set_title('Croston SBA vs Moving Average — Per Item MAE', fontsize=13)
ax.legend()
plt.tight_layout()
plt.show()

import numpy as np
import pandas as pd

# ── Step 1: Build forecast column from Croston fitted_store ────────────────
records = []
for item_id, data in fitted_store.items():
    weeks = weekly_agg[weekly_agg['item_id'] == item_id]['wm_yr_wk'].values
    for i, (act, fit) in enumerate(zip(data['actual'], data['fitted'])):
        records.append({'item_id': item_id, 'wm_yr_wk': weeks[i],
                        'actual': act, 'forecast': fit})

result_df = pd.DataFrame(records)

# ── Step 2: WMAPE function ─────────────────────────────────────────────────
def calculate_wmape(actual, forecast):
    mask = actual > 0
    return (np.sum(np.abs(actual[mask] - forecast[mask])) / np.sum(actual[mask])) * 100

# ── Step 3: Overall WMAPE ──────────────────────────────────────────────────
wmape_overall = calculate_wmape(result_df['actual'].values, result_df['forecast'].values)

# ── Step 4: Per SKU WMAPE ──────────────────────────────────────────────────
sku_wmape = (result_df[result_df['actual'] > 0]
             .groupby('item_id')
             .apply(lambda g: calculate_wmape(g['actual'].values, g['forecast'].values))
             .reset_index(name='wmape'))
sku_wmape['accuracy'] = 100 - sku_wmape['wmape']

# ── Step 5: Print results ──────────────────────────────────────────────────
print("=" * 40)
print(f"  Overall WMAPE    : {wmape_overall:.2f}%")
print(f"  Model Accuracy   : {100 - wmape_overall:.2f}%")
print(f"  Best SKU WMAPE   : {sku_wmape['wmape'].min():.2f}%")
print(f"  Worst SKU WMAPE  : {sku_wmape['wmape'].max():.2f}%")
print(f"  SKUs < 20% WMAPE : {(sku_wmape['wmape'] < 20).sum()} / {len(sku_wmape)}")
print("=" * 40)
print(sku_wmape.sort_values('wmape').to_string(index=False))