# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o6olYqrt6vF1Qcf7P08Avo-NFIZuLNYp
"""

import pandas as pd

def merge_outputs(df1, df2, df3):
    final_df = pd.concat([df1, df2, df3], ignore_index=True)

    # Optional: sort by SKU
    final_df = final_df.sort_values(by="SKU")

    return final_df