# -*- coding: utf-8 -*-
"""Middle_sku.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yrPFK-NIpSZVpahH7LYES_OSCNgbs7GN
"""

!pip install pytrends

import pandas as pd
import numpy as np
from xgboost import XGBRegressor
from pytrends.request import TrendReq
import warnings
import time

# Suppress warnings for clean output
warnings.filterwarnings('ignore')


# --- STEP 1: LOAD INTERNAL DATA ---
df_medium = pd.read_csv('data_medium_skus.csv')
df_master = pd.read_csv('master_data.csv')

# Clean dates and map weeks
df_master['date'] = pd.to_datetime(df_master['date'])
date_map = df_master[['wm_yr_wk', 'date']].dropna().drop_duplicates().groupby('wm_yr_wk')['date'].min().reset_index()
df = pd.merge(df_medium, date_map, on='wm_yr_wk', how='left')


# --- STEP 2: GENERATE WEATHER DATA ---
weeks_dates = df_master[['wm_yr_wk', 'date', 'state_id']].drop_duplicates().dropna()

def simulate_weather(row):
    week_num = int(str(row['wm_yr_wk'])[-2:])
    if row['state_id'] == 'CA': base, amp = 65, 15
    elif row['state_id'] == 'TX': base, amp = 75, 25
    else: base, amp = 45, 40 # WI

    # Sine wave for seasons + random noise
    temp = base + amp * np.sin(2 * np.pi * (week_num - 15) / 52)
    return np.round(temp + np.random.normal(0, 3), 1)

weeks_dates['avg_temp_F'] = weeks_dates.apply(simulate_weather, axis=1)
weeks_dates['extreme_weather'] = ((weeks_dates['avg_temp_F'] < 20) | (weeks_dates['avg_temp_F'] > 95)).astype(int)


# --- STEP 3: FETCH GOOGLE TRENDS ---
try:
    # Adding a timeout to prevent hanging
    pytrends = TrendReq(hl='en-US', tz=360, timeout=(10, 25))
    kw_list = ["Walmart Food", "Walmart Hobbies", "Household supplies"]

    time.sleep(2) # Pause to prevent IP block
    pytrends.build_payload(kw_list, timeframe='2011-01-01 2016-06-01', geo='US')
    df_trends = pytrends.interest_over_time().reset_index()

    # Cleanup Trends data
    if 'isPartial' in df_trends.columns:
        df_trends = df_trends.drop(columns=['isPartial'])
    df_trends = df_trends.rename(columns={'date': 'date_dt'})

except Exception as e:
    # Fallback so the script doesn't crash if Google blocks the request
    df_trends = pd.DataFrame({'date_dt': pd.to_datetime(weeks_dates['date'].unique())})
    for kw in ["Walmart Food", "Walmart Hobbies", "Household supplies"]:
        df_trends[kw] = 50


# --- STEP 4: MERGE EVERYTHING ---
# Merge Weather
df = pd.merge(df, weeks_dates[['wm_yr_wk', 'state_id', 'avg_temp_F', 'extreme_weather']],
              on=['wm_yr_wk', 'state_id'], how='left')

# Merge Trends
df['date_dt'] = pd.to_datetime(df['date'])
df = pd.merge(df, df_trends, on='date_dt', how='left')


# --- STEP 5: FEATURE ENGINEERING ---
df = df.sort_values(['item_id', 'store_id', 'date_dt'])

# 5a. Fourier Seasonality (Replaces Prophet)
df['day_of_year'] = df['date_dt'].dt.dayofyear
df['sin_year'] = np.sin(2 * np.pi * df['day_of_year'] / 365.25)
df['cos_year'] = np.cos(2 * np.pi * df['day_of_year'] / 365.25)

# 5b. Lags & Weather Momentum
df['lag_1'] = df.groupby(['item_id', 'store_id'])['sales_quantity'].shift(1)
df['rolling_mean_4'] = df.groupby(['item_id', 'store_id'])['sales_quantity'].shift(1).transform(lambda x: x.rolling(4).mean())
df['temp_change'] = df['avg_temp_F'].diff()


# --- STEP 6: TRAIN GLOBAL MODEL ---
features = [
    'sell_price', 'dept_total_sales', 'has_event',
    'snap_CA', 'snap_TX', 'snap_WI',
    'avg_temp_F', 'extreme_weather', 'temp_change',
    'sin_year', 'cos_year', 'lag_1', 'rolling_mean_4',
    'Walmart Food', 'Walmart Hobbies', 'Household supplies'
]

# Drop rows with NaN values (required for XGBoost to train properly)
train_df = df.dropna(subset=['lag_1', 'rolling_mean_4', 'Walmart Food']).copy()

X = train_df[features]
y = train_df['sales_quantity']

model = XGBRegressor(n_estimators=200, learning_rate=0.05, max_depth=6, n_jobs=-1, random_state=42)
model.fit(X, y)


# --- STEP 7: PREDICT & SAVE ---
# np.maximum(0, ...) ensures no negative forecasts are predicted
train_df['final_forecast'] = np.maximum(0, model.predict(X))

wmape = (np.abs(train_df['sales_quantity'] - train_df['final_forecast']).sum() / train_df['sales_quantity'].sum()) * 100

print(f"\n Final Global Model WMAPE: {wmape:.2f}%")