# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o6olYqrt6vF1Qcf7P08Avo-NFIZuLNYp
"""

from http.server import BaseHTTPRequestHandler
import json
import pandas as pd
from models.high_model import run_high_model
from models.mid_model import run_mid_model
from models.low_model import run_low_model
from utils.merge import merge_outputs
import io

class handler(BaseHTTPRequestHandler):
    def do_POST(self):
        content_length = int(self.headers['Content-Length'])
        body = self.rfile.read(content_length)

        data = json.loads(body)

        # Convert input JSON to DataFrame
        input_df = pd.DataFrame(data)

        # Run all 3 models
        high_df = run_high_model(input_df)
        mid_df = run_mid_model(input_df)
        low_df = run_low_model(input_df)

        # Merge outputs
        final_df = merge_outputs(high_df, mid_df, low_df)

        # Convert to Excel
        output = io.BytesIO()
        final_df.to_excel(output, index=False)
        output.seek(0)

        # Send response
        self.send_response(200)
        self.send_header("Content-type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
        self.end_headers()
        self.wfile.write(output.read())